### Send event
POST http://localhost:3000/events
Content-Type: application/json

{
  
  "type": "LOGIN",
  "severity": "MEDIUM",
  "timestamp": "2026-01-09T09:30:00Z",
  "payload": {
    "user": "khushi"
  }
}


###

### Fetch events
GET http://localhost:3000/events
